config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  # For detect { ||  }ails on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm
  resources :cocktails, only: [:show, :new, :create]

  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
   mount_uploader :url, UrlUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :cocktails, through: :doses
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
    @image = "banner.jpg"
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :url)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end

  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :amount, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_cocktail_form.html.erb
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.file_field :url %>
  <%= f.hidden_field :url_cache, as: :hidden %>
  <%= f.input :name, label: "my cocktail's name" %>
  <%= f.submit "next", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<!-- nav -->
<%= render 'shared/navbar' %>
<!-- banner -->
<%= render '/shared/banner', image: @image %>
<!-- cocktail list -->
<div class="wrapper">
  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-sm-4">
          <!-- insert <div class="card"> -->
          <%= render '/shared/card', cocktail: cocktail %>
        </div>
      <% end %>
    </div>
    <%= link_to 'share your cocktail', new_cocktail_path, class: "btn btn-primary btn-block mt" %>

  </div>
</div>
<!-- footer -->
<%= render 'shared/footer' %>

app/views/cocktails/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <%= render 'cocktail_form', cocktail: @cocktail %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<!-- nav -->
<%= render 'shared/navbar' %>
<!-- banner -->
<%= render '/shared/banner', cocktail: @cocktail  %>
<!-- cocktail list -->
<div class="wrapper">
  <div class="container">
    <%= render '/shared/list', cocktail: @cocktail  %>
    <%= link_to 'back', cocktails_path, class: "btn btn-primary" %>
  </div>
</div>
<!-- footer -->
<%= render 'shared/footer' %>

app/views/doses/_doses_form.html.erb
<%= simple_form_for [ @cocktail, @dose ],  wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.association :ingredient, input_html: { class: "select2" } %>
  <%= f.input :amount %>
  <%= f.input :description, class: 'input-group-btn'  %>
  <%= f.submit "+", class: "btn btn-primary" %>
<% end %>

app/views/doses/new.html.erb
<div class="wrapper">
  <div class="container">
    <%= render '/shared/list', cocktail: @cocktail  %>
    <div class="row">
      <div class="col d-flex j-c">
        <%= render 'doses_form', cocktail: @cocktail, dose: @dose %>
      </div>
    </div>
    <%= link_to 'save', cocktail_path(@cocktail), class: "btn btn-primary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= @cocktail ?  cl_image_path(@cocktail.url) : image_path(@image) %>);">
  <div class="banner-content">
    <% unless @cocktail %>
      <h1>Mrs Cocktail</h1>
      <p>Find the more popular cocktails</p>
      <form class="form-inline">
      <input type="text" class="form-control mb-2 mr-sm-2" id="search" placeholder="name, ingredient..">
      <button type="submit" class="btn btn-primary mb-2">Search</button>
    </form>
    <% end %>
    <% if @cocktail %>
      <h1><%= @cocktail.name %></h1>
    <% end %>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card mt" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path(cocktail.url) %>);">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2><%= cocktail.name %></h2>
  </div>
  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
  <%= link_to '', cocktail_path(cocktail), class:"card-link" %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Mrs Cocktail INC.
  </div>
</div>

app/views/shared/_list.html.erb
<ul class="list-group">
  <% @cocktail.doses.each do |dose| %>
    <li class="list-group-item"><%= "#{dose.ingredient.name} - #{dose.amount} - #{dose.description} " %></li>
<% end %>
</ul>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo.png", alt: "logo" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">My Cocktails</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Ingredients</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">About</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>